### PR TITLE
[CI]: Fix Blackduck issues

### PR DESCRIPTION
**Pull request by vialogi**
## Description
This change fixes the intermittent BlackDuck failures in CI jobs.

##### What
Replace the NGCI docker image used for the BlackDuck module.

##### Why ?
The old NGCI image is old and not supported by the Lab Infrastructure team

## Change type
What kind of change does this PR introduce?
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [x] CI related changes
- [ ] Documentation content changes
- [ ] Tests
- [ ] Other

## Check list
- [ ] Code follows the style de facto guidelines of this project
- [ ] Comments have been inserted in hard to understand places
- [ ] Documentation has been updated (if necessary)
- [ ] Test has been added (if possible)

### CODE REVIEW

**Comment by dpressle** [comment]
your CI didnt run BD how can we know its working?

**Comment by vialogi** [comment]
bot:retest

**Review by dpressle — APPROVED** [review]

**Comment by dpressle** [comment]
bot:retest

**Comment by dpressle** [comment]
@vialogi please check why it fails in CI

**Pull request closed without merging**
