### PR TITLE
HPCINFRA-2661 [CI]: Copyright format fix

### PR DESCRIPTION
**Pull request by vialogi**
## Description
Fix the Copyright information format template

##### What
Fix the Copyright information format template to be used with header checker

##### Why ?
The format that is in use does not match the required license type ("bsd" ->? "dual_gpt_2_bsd3")

## Change type
What kind of change does this PR introduce?
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [x] CI related changes
- [ ] Documentation content changes
- [ ] Tests
- [ ] Other

## Check list
- [ ] Code follows the style de facto guidelines of this project
- [ ] Comments have been inserted in hard to understand places
- [ ] Documentation has been updated (if necessary)
- [ ] Test has been added (if possible)

### CODE REVIEW

**Comment by vialogi** [comment]
bot:retest

**Comment by vialogi** [comment]
bot:retest

**Comment by vialogi** [comment]
bot:retest

**Review by dpressle — APPROVED** [review]

**Comment by vialogi** [comment]
bot:retest

**Comment by vialogi** [comment]
bot:retest

**Pull request merged**
