### PR TITLE
[CI]: fixing false positives in the Secrets Scanner on doca_xlio_vNext branch

### PR DESCRIPTION
**Pull request by vialogi**
## Description
We update references to Jenkins's secrets

##### What
We update CI with updated Jenkins secrets references

##### Why ?
Secrets Scanner does not work correctly with the old secrets format

## Change type
What kind of change does this PR introduce?
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [x] CI related changes
- [ ] Documentation content changes
- [ ] Tests
- [ ] Other

## Check list
- [ ] Code follows the style de facto guidelines of this project
- [ ] Comments have been inserted in hard to understand places
- [ ] Documentation has been updated (if necessary)
- [ ] Test has been added (if possible)

### CODE REVIEW

**Comment by vialogi** [comment]
bot:retest

**Comment by vialogi** [comment]
bot:retest

**Comment by vialogi** [comment]
bot:retest

**Comment by vialogi** [comment]
bot:retest

**Review by dpressle — APPROVED** [review]

**Pull request merged**
