### PR TITLE
issue: HPCINFRA-1734 [CI] Coverity: upgrade to v2023.12

### PR DESCRIPTION
**Pull request by BasharRadya**
## Description
We're requested to upgrade the Coverity version to 2023.12

##### What
The PR runs Coverity v2023.12 against the Xlio codebase

##### Why ?
_Justification for the PR. If there is existing issue/bug please reference._

##### How ?
_It is optional but for complex PRs please provide information about the design,
architecture, approach, etc._

## Change type
What kind of change does this PR introduce?
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [x] CI related changes
- [ ] Documentation content changes
- [ ] Tests
- [ ] Other

## Check list
- [ ] Code follows the style de facto guidelines of this project
- [ ] Comments have been inserted in hard to understand places
- [ ] Documentation has been updated (if necessary)
- [ ] Test has been added (if possible)

### CODE REVIEW

**Review by iftahl — COMMENTED** [review]
lets squash to 1 commit and describe changes in commit description

**Comment by BasharRadya** [comment]
bot:retest

**Comment by BasharRadya** [comment]
bot:retest

**Comment by BasharRadya** [comment]
bot:retest

**Comment by iftahl** [comment]
replace "HPCINFRA-1734" in commit messages to XLIO's ticket number

**Review by iftahl — APPROVED** [review]

**Comment by galnoam** [comment]
@BasharRadya , please move to fixed

**Pull request merged**
