### PR TITLE
HPCINFRA-2572 secrets scanner

### PR DESCRIPTION
**Pull request by vialogi**
## Description
We update references to Jenkins's secrets

##### What
We update CI with updated Jenkins secrets references

##### Why ?
Secrets Scanner does not work correctly with the old secrets format

## Change type
What kind of change does this PR introduce?
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [x] CI related changes
- [ ] Documentation content changes
- [ ] Tests
- [ ] Other

## Check list
- [ ] Code follows the style de facto guidelines of this project
- [ ] Comments have been inserted in hard to understand places
- [ ] Documentation has been updated (if necessary)
- [ ] Test has been added (if possible)

### CODE REVIEW

**Comment by vialogi** [comment]
bot:retest

**Review by dpressle — APPROVED** [review]

**Review by dpressle — CHANGES_REQUESTED** [review]
missing file changes

**Comment by vialogi** [comment]
> missing file changes

Fixed

**Comment by vialogi** [comment]
Most recent release mode run (on PDC instance): https://nbupdc.blsm.nvidia.com/swx-media-master/job/libxlio/job/LibXLIO-release-dr/2/

**Review by dpressle — APPROVED** [review]

**Review by dpressle — APPROVED** [review]

**Pull request merged**
