### PR TITLE
issue: HPCINFRA-2413 [CI] cppcheck step fixup

### PR DESCRIPTION
**Pull request by vialogi**
## Description
A fixup for cppcheck step in CI, which doesn't work as expected

##### What
_Subject: 
A fix for CI, which doesn't call cppcheck, when DPCP/DOCA compilation is not requested

##### Why ?
_Justification for the PR. 
cppcheck step doesn't do any job when DOCA / DPCP support is not requested

## Change type
What kind of change does this PR introduce?
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [x] CI related changes
- [ ] Documentation content changes
- [ ] Tests
- [ ] Other

## Check list
- [ ] Code follows the style de facto guidelines of this project
- [ ] Comments have been inserted in hard to understand places
- [ ] Documentation has been updated (if necessary)
- [ ] Test has been added (if possible)

### CODE REVIEW

**Comment by vialogi** [comment]
bot:retest

**Review by dpressle — APPROVED** [review]

**Comment by AlexanderGrissik** [comment]
bot:retest

**Comment by vialogi** [comment]
bot:retest

**Comment by AlexanderGrissik** [comment]
bot:retest

**Pull request merged**
